# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airplane < Formula
  desc ""
  homepage "https://airplane.dev"
  version "0.0.1-alpha.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.1-alpha.5/airplane_0.0.1-alpha.5_Darwin_x86_64.tar.gz"
    sha256 "929753242a85902e99670615e404aa32b7ba8770fb2fc9e91b91bc01f0fffb94"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.1-alpha.5/airplane_0.0.1-alpha.5_Darwin_arm64.tar.gz"
    sha256 "7b725b4e08a981e7c2ec9cb0a9afab3737f226e58d7069ec7fbf99e8cbcd2da0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.1-alpha.5/airplane_0.0.1-alpha.5_Linux_x86_64.tar.gz"
    sha256 "eec594933b6bbaf48e3b894d622de0104c6a27fbb57a6ade7d9f856b904581e7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.1-alpha.5/airplane_0.0.1-alpha.5_Linux_arm64.tar.gz"
    sha256 "9c98e8e476606a07fcb30f7090b6043a75b205693a8ef5c18d856de1901593d4"
  end

  def install
    bin.install "airplane"
  end

  test do
    system "#{bin}/airplane help"
  end
end
