# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airplane < Formula
  desc ""
  homepage "https://airplane.dev"
  version "0.0.19"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.19/airplane_darwin_x86_64.tar.gz"
    sha256 "097b6351dd6c45b34b82f6ee9014c68204d5d40c3a7b9a3d8e8fd0ea348010f1"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.19/airplane_darwin_arm64.tar.gz"
    sha256 "e633272c55227030a3bef532ec73efc17d5627f68a1cbd52094dcbae715f7f4b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.19/airplane_linux_x86_64.tar.gz"
    sha256 "0f73d9ace3de16e1a9948261a90efb4dcb8c349d0af5569223c69428d1e84830"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/airplanedev/cli/releases/download/v0.0.19/airplane_linux_arm64.tar.gz"
    sha256 "500dced4be803a1d478c2a2ae1758997d16f442b856cb7fbfafb783ae2c7861c"
  end

  def install
    bin.install "airplane"
  end

  test do
    system "#{bin}/airplane help"
  end
end
